import numpy as np
from matplotlib.colors import ListedColormap
from scipy.ndimage import zoom
from matplotlib import pyplot as plt
from typing import NamedTuple

from fourier import compute_streamfunction
from linalg import rotate_vector, power_range, angle_range


class Phase(NamedTuple):
    theta: float
    phi: float
    z_rotation: bool

class Coil(NamedTuple):
    j_x: np.ndarray
    j_y: np.ndarray
    span: int
    area: float

class Motor(NamedTuple):
    coil: Coil
    phases: list[Phase]



def analyze(motor: Motor):

    #compute the fourier transform of the stream function
    psi = compute_streamfunction(motor.coil.j_x, motor.coil.j_y)


    #scale everything based on grid size and number of spatial periods
    j_size=motor.coil.j_x.shape[0]
    scaling_factor = (motor.coil.span/j_size)**2

    # Target indices for the fundamental frequencies
    dc = int(j_size / 2)
    idx_span = dc + motor.coil.span

    #get the four fundamental force producing components
    # --- X Force Components ---
    cos_x = 2 * psi[dc][idx_span].imag * scaling_factor
    sin_x = 2 * psi[dc][idx_span].real * scaling_factor

    # --- Y Force Components ---
    cos_y = -2 * psi[idx_span][dc].imag * scaling_factor
    sin_y = -2 * psi[idx_span][dc].real * scaling_factor

    # this vector in R4 represents the magnetic field generated by the coil
    fund = np.asarray([cos_x, sin_x, cos_y, sin_y])

    # integrate the current density squared to get the losses
    coil_loss = np.sum(motor.coil.j_x**2 + motor.coil.j_y**2)*scaling_factor

    print(f"Fundamental: {np.linalg.norm(fund)**2:.3f}, Loss={coil_loss:.3f} Area={motor.coil.area:.3f}")

    # the secret sauce. The force from any coil can be scaled up or down by changing physical size or current density
    # this compensates for those effects to produce a normalized value for any coil
    # F^2 / (L * V)
    # we assume the 2D coil is extruded uniformly to form a 3D object - so volume is simplified to area
    # the 0.5 is somewhat arbitrary, it causes the naive current distribution to get a score of 1.0
    fom = 0.5*np.linalg.norm(fund)**2/(coil_loss*motor.coil.area)

    print(f"Figure of merit: {fom:.3f}\n")

    # All coils are identical copies, but with a physical offset
    # this causes their vector to rotate in R4
    # the collection of all the individual coils form a frame (overdetermined basis)
    scaling_factor = 1/np.sqrt(len(motor.phases))
    fund_norm = fund / np.linalg.norm(fund)
    phases = np.empty((4, len(motor.phases)))
    for idx, phase in enumerate(motor.phases):
        v = fund_norm.copy()
        if phase.z_rotation:
            v = np.concatenate([fund_norm[2:], fund_norm[:2]])
        v[0], v[1] = rotate_vector(v[0], v[1], phase.theta)
        v[2], v[3] = rotate_vector(v[2], v[3], phase.phi)
        phases[:, idx] = v.T * scaling_factor

    print("Phase vectors:")
    print(phases)
    print("\n")

    if np.linalg.matrix_rank(phases) != 4:
        print("Motor phases don't span R4! Motor will be unable to apply uniform force for all mover positions")

    #compute the lower/average/upper reconstruction energy (energy required to represent any unit-norm vector in this frame)
    low, avg, high = power_range(phases)

    if np.isclose(low, high, atol=1e-2):
        print("Motor frame is tight, phases are balanced!")
    else:
        print("Motor frame is not tight, phases are unbalanced!")


    print(f"Frame energy between {low*100/4:.1f}% and {high*100/4:.1f}% of ideal (avg: {avg*100/4:.1f}%)")


    small_angle, large_angle = angle_range(phases)

    print(f"Angles between vectors range from {np.rad2deg(small_angle):.1f}° to {np.rad2deg(large_angle):.1f}°")
    if np.isclose(small_angle, large_angle):
        print("Phases are equiangular! (all mutual inductances will be equal)")


    # make the pretty plots
    plt.rcParams.update({
        "text.usetex": False,
        "mathtext.fontset": "stix",
        "font.family": "STIXGeneral"
    })

    fig = plt.figure(figsize=(8, 8), layout='constrained')
    axs = fig.subplot_mosaic(
        [
            ["current_dist", "copper_plot"],
            ["psi_spectrum", "psi"],
         ],
        per_subplot_kw={"psi": {"projection": "3d"}},
    )

    copper_rgb = (0.72, 0.45, 0.20)

    # 2. Create a custom colormap: [0 = transparent, 1 = copper]
    # We use (0,0,0,0) for the alpha channel on the first entry
    cmap = ListedColormap([(0, 0, 0, 0), copper_rgb])

    #assume a constant copper thickness wherever current != 0
    copper = np.where((motor.coil.j_x != 0) | (motor.coil.j_y != 0), 1, 0)

    #build the copper plot by adding shifted copies of the copper distribution from the original coil
    shift_scaling = j_size / (motor.coil.span * 2 * np.pi)
    for phase in motor.phases:
        c = copper
        if phase.z_rotation:
            c = copper.T
        to_plot = np.roll(c, (phase.phi*shift_scaling, phase.theta*shift_scaling), axis=(0, 1))
        axs["copper_plot"].imshow(to_plot, cmap=cmap, alpha=0.8, interpolation="nearest")

    #create the background for the current distribution quiver plot
    n = 1000
    span = np.pi*2*motor.coil.span
    x = np.linspace(0, span, n, endpoint=False)
    y = np.linspace(0, span, n, endpoint=False)
    xv, yv = np.meshgrid(x, y)
    magnet_field = np.cos(xv) + np.cos(yv)
    axs["current_dist"].imshow(magnet_field, extent=(0, span, 0, span), alpha=0.6)

    #resample current distribution onto scale suitable for vector plot
    n_arrows = 50
    disp_jx = zoom(motor.coil.j_x, n_arrows/motor.coil.j_x.shape[0], order=3)
    disp_jy = zoom(motor.coil.j_y, n_arrows/motor.coil.j_y.shape[0], order=3)

    # mask = (abs(disp_jx) > 0.05) | (abs(disp_jy) > 0.05)
    # x_masked = np.where(mask, disp_jx, np.nan)
    # y_masked = np.where(mask, disp_jy, np.nan)

    disp_x = np.linspace(0, span, n_arrows, endpoint=False)
    disp_y = np.linspace(0, span, n_arrows, endpoint=False)
    disp_xv, disp_yv = np.meshgrid(disp_x, disp_y)
    axs["current_dist"].quiver(disp_xv, disp_yv, disp_jx, disp_jy, pivot="mid", color="black",scale=50)

    axs["current_dist"].set_title("Coil Current Distribution",fontsize=16)
    axs["current_dist"].axis("off")

    # plot different spectrum types:
    spectrum_size = 25
    start = int((j_size / 2) - (spectrum_size - 1) / 2)
    end = start + spectrum_size

    max_component = np.max(abs(psi))

    axs["psi_spectrum"].set_title(r"$\psi$ Spectrum",fontsize=16)
    axs["psi_spectrum"].imshow(abs(psi[start:end, start:end]), ) #vmin=0.0, vmax=max_component
    axs["psi_spectrum"].axis("off")
    # axs["magnitude"].magnitude_spectrum(s, Fs=Fs, color='C1')

    psi_spatial = np.fft.ifftn(np.fft.ifftshift(psi)).real

    # 1. Create a spatial meshgrid for the 3D plot
    # (Replace Nx and Ny with the shape of your psi_spatial array)
    Ny, Nx = psi_spatial.shape
    x = np.linspace(0, Nx, Nx)
    y = np.linspace(0, Ny, Ny)
    X, Y = np.meshgrid(x, y)

    # 2. Configure the 3D Axis
    axs["psi"].set_title(r"$\psi$", fontsize=16)

    # 3. Plot the 3D surface
    # 'cmap' adds color shading, 'edgecolor' can be set to 'none' for a smooth look
    surf = axs["psi"].plot_surface(X, Y, psi_spatial, cmap='viridis', edgecolor='none')

    # 4. Turn off the grid/background if you want it completely clean like "axis off"
    axs["psi"].axis("off")
    plt.show()