import sys

import numpy as np
from matplotlib.colors import ListedColormap
from scipy.ndimage import zoom
from matplotlib import pyplot as plt
from typing import NamedTuple

from fourier import get_components, compute_streamfunction
from linalg import rotate_vector, power_range, angle_range


class Phase(NamedTuple):
    theta: float
    phi: float
    z_rotation: bool

class Coil(NamedTuple):
    j_x: np.ndarray
    j_y: np.ndarray
    span: int
    area: float

class Motor(NamedTuple):
    coil: Coil
    phases: list[Phase]



def analyze(motor: Motor):

    #compute the fourier transform of the input current density
    x_spectrum = np.fft.fftshift(np.fft.fftn(motor.coil.j_x))
    y_spectrum = np.fft.fftshift(np.fft.fftn(motor.coil.j_y))

    psi = compute_streamfunction(x_spectrum, y_spectrum)

    #get the four fundamental force producing components
    j_size=motor.coil.j_x.shape[0]
    dc = int(j_size / 2)

    #X force is generated by Y current and vice versa
    cos_x = 2*y_spectrum[dc][dc + motor.coil.span].real / (j_size/motor.coil.span)**2
    sin_x = -2*y_spectrum[dc][dc + motor.coil.span].imag / (j_size/motor.coil.span)**2
    cos_y = 2*x_spectrum[dc + motor.coil.span][dc].real / (j_size/motor.coil.span)**2
    sin_y = -2*x_spectrum[dc + motor.coil.span][dc].imag / (j_size/motor.coil.span)**2

    print(f"x dc energy {abs(x_spectrum[dc, dc])}")
    print(f"y dc energy {abs(y_spectrum[dc, dc])}")

    comp = np.asarray([cos_x, sin_x, cos_y, sin_y])


    x_energy = np.sum((np.abs(x_spectrum)/j_size**2)**2)
    y_energy = np.sum((np.abs(y_spectrum)/j_size**2)**2)

    x_fund_energy = 0.5 * (cos_y**2 + sin_y**2)
    y_fund_energy = 0.5 * (cos_x**2 + sin_x**2)
    x_thd = (x_energy - x_fund_energy) / x_fund_energy
    y_thd = (y_energy - y_fund_energy) / y_fund_energy

    print(f"x THD: {x_thd*100:.1f}%, y THD: {y_thd*100:.1f}%")

    print(f"% fundamental: {x_fund_energy/x_energy}")


    copper = np.where((motor.coil.j_x != 0) | (motor.coil.j_y != 0), 1, 0)

    mag = np.sqrt(motor.coil.j_x**2 + motor.coil.j_y**2)
    scaling = j_size / (motor.coil.span * 2 * np.pi)

    c_plot = np.zeros(motor.coil.j_x.shape)
    total_current = np.zeros(motor.coil.j_x.shape)
    for phase in motor.phases:
        c = copper
        if phase.z_rotation:
            c = copper.T
        c_plot += np.roll(c, (phase.phi*scaling, phase.theta*scaling), axis=(0, 1))
        total_current += np.roll(mag, (phase.phi*scaling, phase.theta*scaling), axis=(0, 1))
    # np.clip(c_plot, 0, 1, out=c_plot)

    print(f"min: {np.min(total_current)}, max: {np.max(total_current)}, avg: {np.average(total_current)}")

    copper_share = (1/(np.maximum(mag, 0.01) / total_current))
    print(np.sum(copper_share)/(j_size**2))#/ len(motor.phases)
    copper_share = np.where(np.isnan(copper_share) | np.isinf(copper_share), 1, copper_share)

    # coil_loss_with_sharing = np.sum((motor.coil.j_x**2 + motor.coil.j_y**2) * copper_share) / j_size**2
    # print(f"coil loss with sharing: {coil_loss_with_sharing}")

    coil_loss = np.sum(motor.coil.j_x**2 + motor.coil.j_y**2) / (j_size/motor.coil.span)**2
    print(f"Fundamental coil efficiency: {0.5*np.linalg.norm(comp)**2/(coil_loss*(motor.coil.area*motor.coil.span**2)):.3f}")
    print(f"fundamental: {np.linalg.norm(comp):.3f}, loss={coil_loss:.3f}")
    area = motor.coil.area*motor.coil.span**2*len(motor.phases)
    scaling_factor = 1/np.sqrt(coil_loss*area/0.5)


    phases = np.empty((4, len(motor.phases)))
    for idx, phase in enumerate(motor.phases):
        p_comp = comp.copy()
        if phase.z_rotation:
            p_comp = np.concatenate([p_comp[2:], p_comp[:2]])
        p_comp[0], p_comp[1] = rotate_vector(p_comp[0], p_comp[1], phase.theta)
        p_comp[2], p_comp[3] = rotate_vector(p_comp[2], p_comp[3], phase.phi)
        phases[:, idx] = p_comp.T * scaling_factor

    print(phases)
    print(np.linalg.matrix_rank(phases))
    low, avg, high = power_range(phases)
    print(f"Power between {low*100/4:.1f}% and {high*100/4:.1f}% of ideal (avg: {avg*100/4:.1f}%)")


    small_angle, large_angle = angle_range(phases)

    print(f"Angles between vectors range from {np.rad2deg(small_angle):.1f}° to {np.rad2deg(large_angle):.1f}°")
    if np.isclose(small_angle, large_angle):
        print("Phases are equiangular!")


    plt.rcParams.update({
        "text.usetex": False,
        "mathtext.fontset": "stix",
        "font.family": "STIXGeneral"
    })

    fig = plt.figure(figsize=(8, 8), layout='constrained')
    axs = fig.subplot_mosaic(
        [
            ["current_dist", "copper_plot"],
            ["psi_spectrum", "psi"],
         ],
        per_subplot_kw={"psi": {"projection": "3d"}},
    )

    copper_rgb = (0.72, 0.45, 0.20)

    # 2. Create a custom colormap: [0 = transparent, 1 = copper]
    # We use (0,0,0,0) for the alpha channel on the first entry
    cmap = ListedColormap([(0, 0, 0, 0), copper_rgb])

    for phase in motor.phases:
        c = copper
        if phase.z_rotation:
            c = copper.T
        to_plot = np.roll(c, (phase.phi*scaling, phase.theta*scaling), axis=(0, 1))
        axs["copper_plot"].imshow(to_plot, cmap=cmap, alpha=0.8, interpolation="nearest")

    #create the background for the current distribution quiver plot
    n = 1000
    span = np.pi*2*motor.coil.span
    x = np.linspace(0, span, n, endpoint=False)
    y = np.linspace(0, span, n, endpoint=False)
    xv, yv = np.meshgrid(x, y)
    magnet_field = np.cos(xv) + np.cos(yv)
    axs["current_dist"].imshow(magnet_field, extent=(0, span, 0, span), alpha=0.6)

    #resample current distribution onto scale suitable for vector plot
    n_arrows = 50
    disp_jx = zoom(motor.coil.j_x, n_arrows/motor.coil.j_x.shape[0], order=3)
    disp_jy = zoom(motor.coil.j_y, n_arrows/motor.coil.j_y.shape[0], order=3)

    # mask = (abs(disp_jx) > 0.05) | (abs(disp_jy) > 0.05)
    # x_masked = np.where(mask, disp_jx, np.nan)
    # y_masked = np.where(mask, disp_jy, np.nan)

    disp_x = np.linspace(0, span, n_arrows, endpoint=False)
    disp_y = np.linspace(0, span, n_arrows, endpoint=False)
    disp_xv, disp_yv = np.meshgrid(disp_x, disp_y)
    axs["current_dist"].quiver(disp_xv, disp_yv, disp_jx, disp_jy, pivot="mid", color="black",scale=50)

    axs["current_dist"].set_title("Coil Current Distribution",fontsize=16)
    axs["current_dist"].axis("off")

    # plot different spectrum types:
    spectrum_size = 25
    start = int((j_size / 2) - (spectrum_size - 1) / 2)
    end = start + spectrum_size

    max_component = np.max(abs(psi))

    axs["psi_spectrum"].set_title(r"$\psi$ Spectrum",fontsize=16)
    axs["psi_spectrum"].imshow(abs(psi[start:end, start:end]), vmin=0.0, vmax=max_component)
    axs["psi_spectrum"].axis("off")
    # axs["magnitude"].magnitude_spectrum(s, Fs=Fs, color='C1')

    psi_spatial = np.fft.ifftn(np.fft.ifftshift(psi)).real

    # 1. Create a spatial meshgrid for the 3D plot
    # (Replace Nx and Ny with the shape of your psi_spatial array)
    Ny, Nx = psi_spatial.shape
    x = np.linspace(0, Nx, Nx)
    y = np.linspace(0, Ny, Ny)
    X, Y = np.meshgrid(x, y)

    # 2. Configure the 3D Axis
    axs["psi"].set_title(r"$\psi$", fontsize=16)

    # 3. Plot the 3D surface
    # 'cmap' adds color shading, 'edgecolor' can be set to 'none' for a smooth look
    surf = axs["psi"].plot_surface(X, Y, psi_spatial, cmap='viridis', edgecolor='none')

    # 4. Turn off the grid/background if you want it completely clean like "axis off"
    axs["psi"].axis("off")
    plt.show()